### ISSUE TITLE
Add vscode debug info

### ISSUE THREAD

**Issue by ssardina** [RMIT-COSC1127-1125-AI24/AI24-DOC#1]
Add how to do debug of autograder in vscode, including json config file

**Comment by ssardina** [comment]
@AndrewPaulChester was this done already?

**Comment by AndrewPaulChester** [comment]
Ah, yes. It turned out there was already an [entry in the FAQ](https://github.com/RMIT-COSC1127-1125-AI24/AI24-DOC/blob/main/FAQ-PROJECTS.md#how-can-i-debug-my-system), but I expanded it.
