### ISSUE TITLE
Update FAQ to include directions to push code/check code is pushed.

### ISSUE THREAD

**Issue by AndrewPaulChester** [RMIT-COSC1127-1125-AI24/AI24-DOC#2]
We are seeing alarming numbers of students who are only pushing their tag, not their code. This gives a warning in github here:
![image](https://github.com/user-attachments/assets/01a4a691-f6da-4ae3-adb5-bfcb19f65ce9)

It seems like sometimes this prevents us from marking the correct code: https://github.com/RMIT-COSC1127-1125-AI24/project-0-warmup/issues/9
But also sometimes doesn't because these were the students with 0 commits in the spreadsheet but got marks.

Either way, we should update our FAQ to explicitly tell students they must push the commits as well, and give a way for them to check. I suspect the increased prevalence of this is because students have literally no understanding of git, and do nothing other than follow our precise instructions to create and push the tag.

@ssardina

**Comment by AndrewPaulChester** [comment]
Also [this post](https://edstem.org/au/courses/15662/discussion/2166989)

![image](https://github.com/user-attachments/assets/0ce30236-2f50-42c0-b430-99759878e1e3)

**Comment by ssardina** [comment]
We should make it clear to push their commits and check that explicitly, will modify P2 form now, though it is late. we can make a full request to everyone later

**Comment by ssardina** [comment]
![image](https://github.com/user-attachments/assets/0faa324f-5bda-4b9c-ba8e-8e8e831087a4)

Can you believe that only 68 people submitted as of Sat 2pm?

**Comment by ssardina** [comment]
Also enriched the FAQs in 2 places:

https://github.com/RMIT-COSC1127-1125-AI24/AI24-DOC/blob/main/SE-PRACTICES.md
![image](https://github.com/user-attachments/assets/dc3ac178-70ee-4bf7-98d0-1e4ee730a4e8)

and in 

https://github.com/RMIT-COSC1127-1125-AI24/AI24-DOC/blob/main/FAQ-PROJECTS.md#how-do-i-submit-my-project-solution-in-my-git-repository-via-tagging
![image](https://github.com/user-attachments/assets/21d96c7a-3c6c-45a5-a0da-b30b531fff3b)


Have a look and refine the text if you think it can be improved @AndrewPaulChester
